const DEFAULT_LOG_LEVEL = "info";
const DEFAULT_BATCH_SIZE = 100;
const DEFAULT_FLUSH_INTERVAL = 5000;
const DEFAULT_MONGO_COLLECTION = "logs";
const DEFAULT_SQL_TABLE = "logs";

export {
  DEFAULT_LOG_LEVEL,
  DEFAULT_BATCH_SIZE,
  DEFAULT_FLUSH_INTERVAL,
  DEFAULT_MONGO_COLLECTION,
  DEFAULT_SQL_TABLE,
};
