const DEFAULT_CONNECT_TIMEOUT_MS = 5000;
const DEFAULT_MAX_RETRIES = 10;
const DEFAULT_RETRY_DELAY_MS = 200;
const DEFAULT_RETRY_MAX_DELAY_MS = 5000;
const DEFAULT_DISABLE_OFFLINE_QUEUE = false;
const KEY_SEPARATOR = ":";
const DEFAULT_JSON_PATH = "$";
const DEFAULT_SCAN_COUNT = 100;
const DEFAULT_INCR_BY = 1;

export {
  DEFAULT_CONNECT_TIMEOUT_MS,
  DEFAULT_MAX_RETRIES,
  DEFAULT_RETRY_DELAY_MS,
  DEFAULT_RETRY_MAX_DELAY_MS,
  DEFAULT_DISABLE_OFFLINE_QUEUE,
  KEY_SEPARATOR,
  DEFAULT_JSON_PATH,
  DEFAULT_SCAN_COUNT,
  DEFAULT_INCR_BY,
};
