const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
} as const;
type HttpStatusCode =
  (typeof HTTP_STATUS_CODES)[keyof typeof HTTP_STATUS_CODES];

const DEFAULT_BODY_LIMIT = "1mb";
const DEFAULT_RATE_LIMIT_WINDOW_MS = 60_000;
const DEFAULT_RATE_LIMIT_MAX = 100;
const GRACEFUL_SHUTDOWN_TIMEOUT_MS = 10_000;
const HEALTH_ENDPOINT_PATH = "/health";
const REQUEST_ID_HEADER = "X-Request-Id";

export {
  HTTP_STATUS_CODES,
  DEFAULT_BODY_LIMIT,
  DEFAULT_RATE_LIMIT_WINDOW_MS,
  DEFAULT_RATE_LIMIT_MAX,
  GRACEFUL_SHUTDOWN_TIMEOUT_MS,
  HEALTH_ENDPOINT_PATH,
  REQUEST_ID_HEADER,
};

export type { HttpStatusCode };
