import type {
  ContextSurfacesConfig,
  DataModel,
  EntityDescription,
  FieldDescription,
  RedisIndexConfig,
  RelationshipDescription,
  CreateSurfaceInput,
  DataSourceConfig,
  RedisConnectionConfig,
  Surface,
  UpdateSurfaceInput,
  ListSurfacesResult,
  CreateAgentKeyInput,
  AgentKey,
  ListAgentKeysResult,
  McpTool,
  McpToolResult,
  McpInitResult,
  LoadRecordsInput,
  LoadRecordsResult,
  Pagination,
  ListOptions,
  KeyValidation,
  HealthResult,
} from "./types";

import { ContextSurfaces } from "./context-surfaces";
import {
  IndexType,
  DistanceMetric,
  OnConflict,
  OnError,
  McpMethod,
} from "./constants";

export { ContextSurfaces, IndexType, DistanceMetric, OnConflict, OnError, McpMethod };

export type {
  ContextSurfacesConfig,
  DataModel,
  EntityDescription,
  FieldDescription,
  RedisIndexConfig,
  RelationshipDescription,
  CreateSurfaceInput,
  DataSourceConfig,
  RedisConnectionConfig,
  Surface,
  UpdateSurfaceInput,
  ListSurfacesResult,
  CreateAgentKeyInput,
  AgentKey,
  ListAgentKeysResult,
  McpTool,
  McpToolResult,
  McpInitResult,
  LoadRecordsInput,
  LoadRecordsResult,
  Pagination,
  ListOptions,
  KeyValidation,
  HealthResult,
};
