const CONFIG_FILENAME = "dataset.config.json";

const TRANSCRIPTS_SUBDIR = "transcripts";
const JSON_EXT = ".json";

const LOGGER_CONTEXT = "MeetingMemory";

const SESSION_ID_PREFIX = "playback";

const DEFAULT_PORT = 3001;
const DEFAULT_AGENT_MEMORY_BASE_URL = "http://localhost:8000";
const DEFAULT_DATA_DIR = "../../data";
const DEFAULT_ACTIVE_DATASET = "wealth-advisor";
const DEFAULT_MODEL_NAME = "gpt-4o-mini";
const DEFAULT_ALLOWED_ORIGINS = ["http://localhost:3000"];

const DEFAULT_LIST_LIMIT = 20;
const DEFAULT_LIST_OFFSET = 0;

const DEFAULT_SEARCH_LIMIT = 20;
const DEFAULT_SEARCH_OFFSET = 0;
const SESSION_SEARCH_LIMIT = 50;
const SEARCH_ALL_LIMIT = 100;

const SUPPORTED_GROUP_BY_FIELDS = ["user_id", "session_id", "namespace"];

export {
  CONFIG_FILENAME,
  TRANSCRIPTS_SUBDIR,
  JSON_EXT,
  LOGGER_CONTEXT,
  SESSION_ID_PREFIX,
  DEFAULT_PORT,
  DEFAULT_AGENT_MEMORY_BASE_URL,
  DEFAULT_DATA_DIR,
  DEFAULT_ACTIVE_DATASET,
  DEFAULT_MODEL_NAME,
  DEFAULT_ALLOWED_ORIGINS,
  DEFAULT_LIST_LIMIT,
  DEFAULT_LIST_OFFSET,
  DEFAULT_SEARCH_LIMIT,
  DEFAULT_SEARCH_OFFSET,
  SESSION_SEARCH_LIMIT,
  SEARCH_ALL_LIMIT,
  SUPPORTED_GROUP_BY_FIELDS,
};
