const CONFIG_FILENAME = "dataset.config.json";
const CLIENT_DATA_FILENAME = "client-data.json";

const TRANSCRIPTS_SUBDIR = "transcripts";
const JSON_EXT = ".json";

const LOGGER_CONTEXT = "MeetingMemory";

const SESSION_ID_PREFIX = "playback";

const DEFAULT_PORT = 3001;
const DEFAULT_LLM_MODEL = "gpt-4o-mini";
const DEFAULT_DATA_DIR = "../../data";
const DEFAULT_ACTIVE_DATASET = "wealth-advisor";
const DEFAULT_CONTEXT_WINDOW_MAX = 1500;
const DEFAULT_ALLOWED_ORIGINS = ["http://localhost:3000"];

const DEFAULT_LIST_LIMIT = 100;
const DEFAULT_LIST_OFFSET = 0;

const AGENT_SEARCH_DEFAULT_LIMIT = 50;
const AGENT_SESSION_LIST_DEFAULT_LIMIT = 100;
const AGENT_SESSION_MEMORIES_LIMIT = 100;

const COPILOTKIT_ENDPOINT = "/copilotkit";
const COPILOTKIT_GRAPH_ID = "memoryAgent";
const DEFAULT_LANGGRAPH_DEPLOYMENT_URL = "http://localhost:2024";

const COPILOT_KEY_PREFIX = "copilot";
const COPILOT_SUGGESTIONS_PREFIX = "suggestions";
const COPILOT_TOPICS_PREFIX = "topics";
const COPILOT_CHUNKS_PREFIX = "chunks";
const COPILOT_KEY_SEPARATOR = ":";

const SUGGESTION_CHUNK_WINDOW = 10;
const QUERY_EXTRACTION_MAX_TOKENS = 100;

const REDIS_JSON_ROOT_PATH = "$";

const DEFAULT_RATE_LIMIT_MAX = 8000;

const DEFAULT_REDIS_URL = "";


const DEFAULT_STATIC_DIR = "../public";

const DEFAULT_LOG_DIR = "../../logs";
const DEFAULT_LOG_FILE = "meeting-memory.log";
const DEFAULT_ERROR_LOG_FILE = "meeting-memory-error.log";
const DEFAULT_LOG_MAX_FILES = 14;

const DetectedTopicStatus = {
  PENDING: "pending",
  DISCUSSED: "discussed",
  NEW: "new",
  QUESTION: "question",
} as const;
type DetectedTopicStatus =
  (typeof DetectedTopicStatus)[keyof typeof DetectedTopicStatus];

const DetectedTopicSource = {
  PRE_SEEDED: "pre-seeded",
  AI_DETECTED: "ai-detected",
} as const;
type DetectedTopicSource =
  (typeof DetectedTopicSource)[keyof typeof DetectedTopicSource];

const SURFACE_SETUP_POLL_INTERVAL_MS = 3000;
const SURFACE_SETUP_POLL_TIMEOUT_MS = 90000;

const DEFAULT_REDIS_PORT = "6379";
const REDIS_TLS_PROTOCOL = "rediss:";
const DEFAULT_REDIS_USERNAME = "default";

const CTX_DATA_SOURCE_TYPE = "redis";
const CTX_DATA_SOURCE_NAME = "demo-redis";

export {
  CONFIG_FILENAME,
  CLIENT_DATA_FILENAME,
  SURFACE_SETUP_POLL_INTERVAL_MS,
  SURFACE_SETUP_POLL_TIMEOUT_MS,
  DEFAULT_REDIS_PORT,
  REDIS_TLS_PROTOCOL,
  DEFAULT_REDIS_USERNAME,
  CTX_DATA_SOURCE_TYPE,
  CTX_DATA_SOURCE_NAME,
  TRANSCRIPTS_SUBDIR,
  JSON_EXT,
  LOGGER_CONTEXT,
  SESSION_ID_PREFIX,
  DEFAULT_PORT,
  DEFAULT_LLM_MODEL,
  DEFAULT_DATA_DIR,
  DEFAULT_ACTIVE_DATASET,
  DEFAULT_CONTEXT_WINDOW_MAX,
  DEFAULT_ALLOWED_ORIGINS,
  DEFAULT_LIST_LIMIT,
  DEFAULT_LIST_OFFSET,
  AGENT_SEARCH_DEFAULT_LIMIT,
  AGENT_SESSION_LIST_DEFAULT_LIMIT,
  AGENT_SESSION_MEMORIES_LIMIT,
  COPILOTKIT_ENDPOINT,
  COPILOTKIT_GRAPH_ID,
  DEFAULT_LANGGRAPH_DEPLOYMENT_URL,
  COPILOT_KEY_PREFIX,
  COPILOT_SUGGESTIONS_PREFIX,
  COPILOT_TOPICS_PREFIX,
  COPILOT_CHUNKS_PREFIX,
  COPILOT_KEY_SEPARATOR,
  SUGGESTION_CHUNK_WINDOW,
  QUERY_EXTRACTION_MAX_TOKENS,
  DEFAULT_RATE_LIMIT_MAX,
  REDIS_JSON_ROOT_PATH,
  DEFAULT_REDIS_URL,
  DEFAULT_STATIC_DIR,
  DEFAULT_LOG_DIR,
  DEFAULT_LOG_FILE,
  DEFAULT_LOG_MAX_FILES,
  DEFAULT_ERROR_LOG_FILE,
  DetectedTopicStatus,
  DetectedTopicSource,
};
