const DEFAULT_SIMILARITY_THRESHOLD = 0.9;
const DEFAULT_TTL_MILLIS = 600_000;

const HEALTH_PROBE_PROMPT = "__health__";
const HEALTH_PROBE_THRESHOLD = 1;

export {
  DEFAULT_SIMILARITY_THRESHOLD,
  DEFAULT_TTL_MILLIS,
  HEALTH_PROBE_PROMPT,
  HEALTH_PROBE_THRESHOLD,
};
